/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-07-06 08:40:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.DeaJeon;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/DeaJeon/../include/nav.jsp", Long.valueOf(1594022972386L));
    _jspx_dependants.put("/WEB-INF/views/DeaJeon/../include/footer.jsp", Long.valueOf(1594024797884L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-jstl-1.2.jar", Long.valueOf(1587602298702L));
    _jspx_dependants.put("jar:file:/C:/Users/Bymtech/Desktop/CMS/web/board%20-%20ing/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/board/WEB-INF/lib/jstl-jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/Bymtech/Desktop/CMS/web/board%20-%20ing/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/board/WEB-INF/lib/jstl-jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t\t<script src='https://code.jquery.com/jquery-3.3.1.min.js'></script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t\t\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t\t\t<meta name=\"author\" content=\"\">\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"/resources/css/style.css\"/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<title>버스광고시스템</title>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<!-- Navigation -->\r\n");
      out.write("\t\t<header class=\"navbar navbar-expand-lg fixed-top\" id=\"mainNav\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Navigation -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"container border-top-red border-bottom-red\" id=\"navcontainer\">\r\n");
      out.write("\t\t\t<a href=\"/\"><img class =\"logo_img\" src = \"/resources/img/index/logo.png\" alt=\"\" ></a>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item mx-0 mx-lg-1\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../bymt/admin\">버스 광고 서비스 로그인</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Main -->\r\n");
      out.write("\t\t<div class=\"container\" id=\"announcementmain\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"announcement_top\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<span class = title_span><strong>버스 광고 서비스</strong></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"announcement_bottom text-center\">\r\n");
      out.write("\t\t\t\t<form name=\"ex_1\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"ex_1\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"급행1\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"ex_2\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"ex_2\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"급행2\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"ex_3\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"ex_3\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"급행3\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_1001\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_1001\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"1001\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_1002\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_1002\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"1002\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_101\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_101\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"101\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_102\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_102\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"102\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_103\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_103\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"103\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_104\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_104\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"104\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_105\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_105\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"105\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_106\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_106\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"106\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_107\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_107\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"107\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_108\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_108\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"108\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_113\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_113\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"113\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_114\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_114\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"114\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_115\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_115\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"115\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_119\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_119\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"119\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_201\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_201\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"201\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_202\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_202\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"202\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_203\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_203\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"203\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_211\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_211\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"211\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_216\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_216\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"216\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_301\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_301\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"301\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_311\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_311\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"311\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_311\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_312\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"312\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_313\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_313\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"313\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_314\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_314\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"314\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_315\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_315\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"315\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_316\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_316\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"316\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_318\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_318\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"318\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_501\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_501\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"501\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_511\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_511\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"511\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_512\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_512\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"512\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_513\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_513\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"513\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_514\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_514\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"514\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_601\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_601\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"601\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_602\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_602\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"602\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_603\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_603\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"603\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_604\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_604\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"604\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_605\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_605\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"605\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_607\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_607\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"607\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_608\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_608\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"608\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_611\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_611\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"611\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_613\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_613\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"613\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_615\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_615\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"615\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_616\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_616\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"616\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_617\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_617\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"617\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_618\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_618\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"618\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_619\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_619\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"619\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_701\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_701\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"701\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_703\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_703\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"703\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_704\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_704\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"704\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_705\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_705\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"705\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_706\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_706\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"706\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_711\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_711\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"711\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_802\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_802\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"802\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_116\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_116\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"116\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_117\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_117\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"117\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_121\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_121\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"121\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_212\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_212\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"212\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_317\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_317\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"317\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_606\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_606\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"606\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_612\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_612\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"612\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_614\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_614\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"614\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_620\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_620\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"620\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_622\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_622\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"622\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_712\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_712\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"712\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_911\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_911\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"911\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_912\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_912\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"912\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_916\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_916\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"916\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_918\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_918\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"918\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_11\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_11\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"11\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_17\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_17\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"17\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_41\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_41\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"41\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_42\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_42\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"42\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_46\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_46\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"46\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_20\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_20\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"20\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_21\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_21\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"21\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_22\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_22\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"22\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_23\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_23\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"23\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_24\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_24\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"24\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_25\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_25\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"25\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_26\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_26\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"26\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_27\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_27\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"27\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_30\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_30\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"30\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_31\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_31\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"31\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_32\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_32\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"32\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_33\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_33\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"33\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_34\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_34\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"34\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_52\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_52\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"52\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_60\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_60\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"60\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_61\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_61\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"61\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_62\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_62\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"62\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_63\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_63\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"63\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_66\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_66\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"66\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_71\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_71\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"71\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_72\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_72\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"72\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_73\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_73\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"73\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_74\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_74\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"74\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"BN_75\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"BN_75\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"75\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"CE_1\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"CE_1\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"첨단1\"/>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"town_1\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"town_1\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"마을1\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"town_2\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"town_2\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"마을2\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<form name=\"town_3\" action=\"/DeaJeon/list\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"busNum\" value=\"town_3\" />\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name= busName value =\"마을3\"/>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<table class = \"bus_list\">\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"6\"> <strong><a>대전광역시 시내버스</a></strong></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr  class =\"bus_title1\">\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"6\"> <strong><a class = \"white_txt\">급행버스</a></strong></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"2\"><a class = \"red_txt\" href=\"#\" onclick=\"javascript:document.ex_1.submit();\">급행1</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"2\"><a class = \"red_txt\" href=\"#\" onclick=\"javascript:document.ex_2.submit();\">급행2</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"2\"><a class = \"red_txt\" href=\"#\" onclick=\"javascript:document.ex_3.submit();\">급행3</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr class =\"bus_title1\">\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"6\"> <strong><a class = \"white_txt\">광역버스</a></strong></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"3\"><a class = \"red_txt\" href=\"#\" onclick=\"javascript:document.BN_1001.submit();\">1001</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"3\"><a class = \"red_txt\" href=\"#\" onclick=\"javascript:document.BN_1002.submit();\">1002</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr  class =\"bus_title2\">\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"6\"><strong><a class = \"white_txt\">간선버스</a></strong></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_101.submit();\">101</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_102.submit();\">102</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_103.submit();\">103</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_104.submit();\">104</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_105.submit();\">105</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_106.submit();\">106</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_107.submit();\">107</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_108.submit();\">108</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_113.submit();\">113</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_114.submit();\">114</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_115.submit();\">115</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_119.submit();\">119</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_201.submit();\">201</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_202.submit();\">202</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_203.submit();\">203</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_211.submit();\">211</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_216.submit();\">216</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_301.submit();\">301</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_311.submit();\">311</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_312.submit();\">312</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_313.submit();\">313</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_314.submit();\">314</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_315.submit();\">315</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_316.submit();\">316</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_318.submit();\">318</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_501.submit();\">501</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_511.submit();\">511</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_512.submit();\">512</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_513.submit();\">513</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_514.submit();\">514</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_601.submit();\">601</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_602.submit();\">602</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_603.submit();\">603</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_604.submit();\">604</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_605.submit();\">605</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_607.submit();\">607</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_608.submit();\">608</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_611.submit();\">611</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_613.submit();\">613</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_615.submit();\">615</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_616.submit();\">616</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_617.submit();\">617</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_618.submit();\">618</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_619.submit();\">619</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_701.submit();\">701</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_703.submit();\">703</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_704.submit();\">704</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_705.submit();\">705</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"2\"><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_706.submit();\">706</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"2\"><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_711.submit();\">711</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"2\"><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.BN_802.submit();\">802</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr  class =\"bus_title3\">\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"6\"><strong><a class = \"white_txt\">지선버스</a></strong></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_116.submit();\">116</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_117.submit();\">117</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_121.submit();\">121</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_212.submit();\">212</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_317.submit();\">317</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_606.submit();\">606</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_612.submit();\">612</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_614.submit();\">614</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_620.submit();\">620</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_622.submit();\">622</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_712.submit();\">712</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_911.submit();\">911</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"2\"><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_912.submit();\">912</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"2\"><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_916.submit();\">916</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"2\"><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_918.submit();\">918</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr  class =\"bus_title3\">\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"6\"><strong><a class = \"white_txt\">외곽버스</a></strong></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class= \"bus_title3\"><a class = \"white_txt\">유성구</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_11.submit();\">11</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_17.submit();\">17</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_41.submit();\">41</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_42.submit();\">42</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_46.submit();\">46</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td rowspan=\"2\" class= \"bus_title3\"><a class = \"white_txt\">서구</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_20.submit();\">20</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_21.submit();\">21</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_22.submit();\">22</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_23.submit();\">23</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_24.submit();\">24</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_25.submit();\">25</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_26.submit();\">26</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_27.submit();\">27</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\"></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\"></a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class= \"bus_title3\"><a class = \"white_txt\">중구</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_30.submit();\">30</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_31.submit();\">31</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_32.submit();\">32</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_33.submit();\">33</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_34.submit();\">34</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td rowspan=\"2\" class= \"bus_title3\"><a class = \"white_txt\">동구</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_52.submit();\">52</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_60.submit();\">60</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_61.submit();\">61</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_62.submit();\">62</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_63.submit();\">63</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_607.submit();\">66</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\"></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\"></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\"></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\"></a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class= \"bus_title3\"><a class = \"white_txt\">대덕구</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_71.submit();\">71</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_72.submit();\">72</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_73.submit();\">73</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_74.submit();\">74</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.BN_75.submit();\">75</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td class= \"bus_title3\"><a class = \"white_txt\">맞춤</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\" href=\"#\" onclick=\"javascript:document.CE1.submit();\">첨단1</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\"></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\"></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\"></a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><a class = \"green_txt\"></a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr  class =\"bus_title2\">\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"6\"><strong><a class = \"white_txt\">마을버스</a></strong></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"2\"><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.town1.submit();\">마을1</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"2\"><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.town2.submit();\">마을2</a></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan =\"2\"><a class = \"blue_txt\" href=\"#\" onclick=\"javascript:document.town3.submit();\">마을3</a></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- Footer -->\t\r\n");
      out.write("\t    <footer class=\"footer\" id=\"footer\">\r\n");
      out.write("\t\t    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"address\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<p class=\" txtBase\">\r\n");
      out.write("\t\t\t\t\t대표자(성명) : 김병용&nbsp;&nbsp;사업자 등록번호 : 375-85-00293, 314-86-5779<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t포항 \t본사 \t주소 : (37748) 경북 포항시 북구 중흥로 265 (죽도동) 성원메디컬 108호<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t대전 연구소 주소 : (34013) 대전광역시 유성구 테크노 4로 17 (관평동) 대덕비즈센터 A동 207호, 208호<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t전화 : 070-4265-3411&nbsp;&nbsp;팩스 : 070-4015-0616\r\n");
      out.write("\t\t\t\t</p> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/resources/jquery/jstyle.js\"></script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/DeaJeon/main.jsp(33,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<div class =\"admin_menu\">\r\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<button type=\"button\" id=\"logout_btn\"> 로그아웃</button>\r\n");
          out.write("\t\t\t\t\t\t<script>\t\r\n");
          out.write("\t\t\t\t\t\t$(\"#logout_btn\").click(function(){\r\n");
          out.write("\t\t\t\t\t\t\tself.location = \"../bymt/logout\";\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t});\r\n");
          out.write("\t\t\t\t\t\t</script>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/DeaJeon/main.jsp(35,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AreaNum == '1' || AreaNum == '2'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<button type=\"button\" id=\"write_btn\">광고 올리기</button>\r\n");
          out.write("\t\t\t\t\t\t\t<script>\t\r\n");
          out.write("\t\t\t\t\t\t\t\t$(\"#write_btn\").click(function(){\r\n");
          out.write("\t\t\t\t\t\t\t\t\tself.location = \"./write\";\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t});\r\n");
          out.write("\t\t\t\t\t\t\t</script>\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
