/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-07-06 08:15:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.DeaJeon;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class write_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/DeaJeon/../include/nav.jsp", Long.valueOf(1594022972386L));
    _jspx_dependants.put("/WEB-INF/views/DeaJeon/../include/footer.jsp", Long.valueOf(1587633888914L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-jstl-1.2.jar", Long.valueOf(1587602298702L));
    _jspx_dependants.put("jar:file:/C:/Users/Bymtech/Desktop/CMS/web/board%20-%20ing/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/board/WEB-INF/lib/jstl-jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/C:/Users/Bymtech/Desktop/CMS/web/board%20-%20ing/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/board/WEB-INF/lib/jstl-jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t\t\t<script src='https://code.jquery.com/jquery-3.3.1.min.js'></script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t\t\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t\t\t<meta name=\"author\" content=\"\">\r\n");
      out.write("\t\t\t<link rel=\"stylesheet\" href=\"/resources/css/style.css\"/>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\tfunction formCheck() { \r\n");
      out.write("\t\t\t\tvar title = document.forms[0].title;\r\n");
      out.write("\t\t\t\tvar content = document.forms[0].content; \r\n");
      out.write("\t\t\t\tvar busNum = document.forms[0].busNum; \r\n");
      out.write("\t\t\t\tvar upfile=document.forms[0].upfile;\r\n");
      out.write("\t\t\t\tvar file= upfile.value;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(file.substr(file.length-3) == \"\"){\r\n");
      out.write("\t\t\t\t\talert('파일을 선택하지 않으셨습니다.');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}else if(file.match(/[_0-9a-zA-Z-][0-9a-zA-Z-]+.mp4/) == null){\r\n");
      out.write("\t\t\t\t\talert('파일은 영어와 숫자,-,_만 사용하실수 있으며 mp4형식만 가능합니다.');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif (busNum.value ==\"1\"){\r\n");
      out.write("\t\t\t\t\talert('게시판을 선택하지 않으셨습니다.');\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif (title.value == null || title.value == \"\"){                                   \r\n");
      out.write("\t\t\t\t\talert('제목을 입력하지 않으셨습니다.');                                  \r\n");
      out.write("\t\t\t\t\tdocument.forms[0].title.focus();                          \r\n");
      out.write("\t\t\t\t\t return false;                                                     \r\n");
      out.write("\t\t\t\t}else if(title.value.indexOf(\"'\") != -1 ||\r\n");
      out.write("\t\t\t\t\t\ttitle.value.indexOf(\"&\") != -1 ||\r\n");
      out.write("\t\t\t\t\t\ttitle.value.indexOf(\"*\") != -1 ||\r\n");
      out.write("\t\t\t\t\t\ttitle.value.indexOf(\"_\") != -1 ||\r\n");
      out.write("\t\t\t\t\t\ttitle.value.indexOf(\"--\") != -1 ||\r\n");
      out.write("\t\t\t\t\t\ttitle.value.indexOf(\";\") != -1\r\n");
      out.write("\t\t\t\t\t\t){\r\n");
      out.write("\t\t\t\t      alert(\"',&,*,_,--,; 와 같은 문자는 입력하실 수 없습니다.\");\r\n");
      out.write("\t\t\t\t      title.focus();\r\n");
      out.write("\t\t\t\t      return false;\r\n");
      out.write("\t\t\t\t }\t\r\n");
      out.write("\t\t\t\tif (content.value == null || content.value == \"\"){                                   \r\n");
      out.write("\t\t\t\t\talert('영상에 대한 설명을 적어주세요.');                                  \r\n");
      out.write("\t\t\t\t\tdocument.forms[0].content.focus();                          \r\n");
      out.write("\t\t\t\t\treturn false;                                                     \r\n");
      out.write("\t\t\t\t}else if(content.value.indexOf(\"'\") != -1 ||\r\n");
      out.write("\t\t\t\t\t\tcontent.value.indexOf(\"&\") != -1 ||\r\n");
      out.write("\t\t\t\t\t\tcontent.value.indexOf(\"*\") != -1 ||\r\n");
      out.write("\t\t\t\t\t\tcontent.value.indexOf(\"_\") != -1 ||\r\n");
      out.write("\t\t\t\t\t\tcontent.value.indexOf(\"--\") != -1 ||\r\n");
      out.write("\t\t\t\t\t\tcontent.value.indexOf(\";\") != -1\r\n");
      out.write("\t\t\t\t\t\t){\r\n");
      out.write("\t\t\t\t      alert(\"',&,*,_,--,; 와 같은 문자는 입력하실 수 없습니다.\");\r\n");
      out.write("\t\t\t\t      content.focus();\r\n");
      out.write("\t\t\t\t      return false;\r\n");
      out.write("\t\t\t\t }\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t<script>\r\n");
      out.write("\t\t\t\tfunction changeSelect(selectObject)\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t     var busNum = selectObject.value;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<title>바이엠텍</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<!-- Navigation -->\r\n");
      out.write("\t\t<header class=\"navbar navbar-expand-lg fixed-top\" id=\"mainNav\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Navigation -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"container border-top-red border-bottom-red\" id=\"navcontainer\">\r\n");
      out.write("\t\t\t<a href=\"/\"><img class =\"logo_img\" src = \"/resources/img/index/logo.png\" alt=\"\" ></a>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item mx-0 mx-lg-1\">\r\n");
      out.write("\t\t\t\t\t\t<a href=\"../bymt/admin\">버스 광고 서비스 로그인</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\t</header>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Main -->\r\n");
      out.write("\t\t<div class=\"container\" id=\"announcementmain\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"announcement_top\">\r\n");
      out.write("\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t<span  class = title_span><strong>광고 올리기</strong></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"announcement_bottom text-center\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t \r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Footer -->\t\r\n");
      out.write("\t    <footer class=\"footer\" id=\"footer\">\r\n");
      out.write("\t\t    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"address\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<p class=\" txtBase\">\r\n");
      out.write("\t\t\t\t\t대표자(성명) : 김병용&nbsp;&nbsp;사업자 등록번호 : 375-85-00293, 314-86-5779<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t포항 \t본사 \t주소 : (37748) 경북 포항시 북구 중흥로 265 (죽도동) 성원메디컬 108호<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t대전 연구소 주소 : (34027) 대전광역시 유성구 테크노9로 35 (탑립동) 지능로봇산업화센터 401호 <br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t전화 : 070-4265-3411&nbsp;&nbsp;팩스 : 070-4015-0616&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"../board/write\"><img class=mail src=\"/resources/img/index/mail.png\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t</p> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/resources/jquery/jstyle.js\"></script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/DeaJeon/write.jsp(92,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<div class =\"admin_menu\">\r\n");
          out.write("\t\t\t\t\t\t<button type=\"button\" id=\"logout_btn\"> 로그아웃</button>\r\n");
          out.write("\t\t\t\t\t\t<script>\t\r\n");
          out.write("\t\t\t\t\t\t$(\"#logout_btn\").click(function(){\r\n");
          out.write("\t\t\t\t\t\t\tself.location = \"../bymt/logout\";\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t});\r\n");
          out.write("\t\t\t\t\t\t</script>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/DeaJeon/write.jsp(104,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/DeaJeon/write.jsp(105,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${AreaNum == '1' || AreaNum == '2'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t<form role=\"form\" action=\"/DeaJeon/write\" method=\"post\" autocomplete=\"off\" enctype=\"multipart/form-data\" onsubmit=\"return formCheck();\">\r\n");
          out.write("\t\t\t\t\t\t\t<div>\r\n");
          out.write("\t\t\t\t\t\t\t\t버스 노선 :\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<select name=\"busNum\" id=\"busNum\" onChange=\"changeSelect(this)\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<option value=\"1\">--</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<optgroup label=\"급행\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"ex_1\">급행1</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"ex_2\">급행2</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"ex_3\">급행3</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</optgroup>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<optgroup label=\"광역\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_1001\">1001</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_1002\">1002</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</optgroup>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<optgroup label=\"간선\">  \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_101\">101</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_102\">102</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_103\">103</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_104\">104</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_105\">105</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_106\">106</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_107\">107</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_108\">108</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_113\">113</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_114\">114</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_115\">115</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_119\">119</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_201\">201</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_202\">202</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_203\">203</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_211\">211</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_216\">216</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_301\">301</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_311\">311</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_312\">312</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_313\">313</option>  \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_314\">314</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_315\">315</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_316\">316</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_318\">318</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_501\">501</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_511\">511</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_512\">512</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_513\">513</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_514\">514</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_601\">601</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_602\">602</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_603\">603</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_604\">604</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_605\">605</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_607\">607</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_608\">608</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_611\">611</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_613\">613</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_615\">615</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_616\">616</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_617\">617</option>  \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_618\">618</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_619\">619</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_701\">701</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_703\">703</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_704\">704</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_705\">705</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_706\">706</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_711\">711</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_802\">802</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</optgroup> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<optgroup label=\"지선\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_116\">116</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_117\">117</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_121\">121</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_212\">212</option>  \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_317\">317</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_606\">606</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_612\">612</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_614\">614</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_620\">620</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_622\">622</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_712\">712</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_911\">911</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_912\">912</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_916\">916</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_918\">918</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</optgroup>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<optgroup label=\"유성구\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_11\">11</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_17\">17</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_41\">41</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_42\">42</option>  \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_46\">46</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</optgroup>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<optgroup label=\"서구\"> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_20\">20</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_21\">21</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_22\">22</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_23\">23</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_24\">24</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_25\">25</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_26\">26</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_27\">27</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</optgroup>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<optgroup label=\"중구\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_30\">30</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_31\">31</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_32\">32</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_33\">33</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_34\">34</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</optgroup>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<optgroup label=\"동구\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_52\">52</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_60\">60</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_61\">61</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_62\">62</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_63\">63</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_66\">66</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</optgroup>\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<optgroup label=\"대덕구\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_71\">71</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_72\">72</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_73\">73</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_74\">74</option>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"BN_75\">75</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</optgroup>\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<optgroup label=\"맞춤\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"CE_1\">첨단1</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</optgroup>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<optgroup label=\"마을\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"town_1\">마을1</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"town_2\">마을2</option> \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"town_3\">마을3</option>   \r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</optgroup>\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</select>\r\n");
          out.write("\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t<table>\r\n");
          out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td class =\"announcement_title2\">제목</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td class =\"announcement_title4\"><input type=\"text\" name=\"title\" /></td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td class =\"announcement_title2\">작성자</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td class =\"announcement_title4\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" name=\"writer\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.adminName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" readonly=\"readonly\" />\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</td>\t\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
          out.write("\t\t\t\t\t\t\t</table>\r\n");
          out.write("\t\t\t\t\t\t\t<table>\r\n");
          out.write("\t\t\t\t\t\t\t\t<tbody>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t<tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t<td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<div class =\"announcement_content\">\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t<textarea cols=\"50\" rows=\"5\" name=\"content\" class=\"inputbox announce_content\"></textarea>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t</td>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t</tr>\r\n");
          out.write("\t\t\t\t\t\t\t\t</tbody>\r\n");
          out.write("\t\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t</table>\r\n");
          out.write("\t\t\t\t\t\t\t<div>\r\n");
          out.write("\t\t\t\t\t\t\t\t<label for = \"File\">광고파일 : </label>\r\n");
          out.write("\t\t\t\t\t\t\t\t<input type=\"file\" id = \"upfile\" name=\"upfile\"/>\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t\r\n");
          out.write("\t\t\t\t\t\t\t<button class=\"btn\" type=\"submit\">작성</button>\r\n");
          out.write("\t\t\t\t\t\t\t<button class=\"btn\" type=\"button\" id=\"cancel_btn\"> 취소</button>\r\n");
          out.write("\t\t\t\t\t\t\t<script>\t\r\n");
          out.write("\t\t\t\t\t\t\t\t$(\"#cancel_btn\").click(function(){\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\twindow.history.back();\r\n");
          out.write("\t\t\t\t\t\t\t\t});\r\n");
          out.write("\t\t\t\t\t\t\t</script>\r\n");
          out.write("\t\t\t\t\t\t</form>\r\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/DeaJeon/write.jsp(281,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<p>로그인을 하셔야 해당 페이지를 볼 수 있습니다.</p>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
