/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.53
 * Generated at: 2020-05-08 02:28:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.sub;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class goods_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/jstl-jstl-1.2.jar", Long.valueOf(1587602298702L));
    _jspx_dependants.put("/WEB-INF/views/sub/../include/nav.jsp", Long.valueOf(1587715402256L));
    _jspx_dependants.put("/WEB-INF/views/sub/../include/sidenav.jsp", Long.valueOf(1587629586554L));
    _jspx_dependants.put("jar:file:/C:/Users/Bymtech/Desktop/hompage/board/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/board/WEB-INF/lib/jstl-jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/sub/../include/footer.jsp", Long.valueOf(1587633888914L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<meta charset=\"utf-8\">\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t\t<meta name=\"description\" content=\"\">\r\n");
      out.write("\t\t<meta name=\"author\" content=\"\">\r\n");
      out.write("\t\t<link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<title>바이엠텍</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<!-- Navigation -->\r\n");
      out.write("\t\t<nav class=\"navbar navbar-expand-lg fixed-top\" id=\"mainNav\">\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Navigation -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t<div class=\"container border-top-red border-bottom-red\" id=\"navcontainer\">\r\n");
      out.write("\t\t\t<a href=\"/\"><img class =\"logo_img\" src = \"/resources/img/index/logo.png\" alt=\"\" ></a>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item mx-0 mx-lg-1\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link\" href=/sub/company>회사소개</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class= \"submenu navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"/sub/company\" >인사말</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"/sub/history\" >연혁</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"/sub/location\" >찾아오시는 길</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item mx-0 mx-lg-1\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link \" href=\"/sub/business\">사업소개</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item mx-0 mx-lg-1\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link \" href=\"/sub/goods\">제품소개</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item mx-0 mx-lg-1\">\r\n");
      out.write("\t\t\t\t\t\t<a class=\"nav-link \" href=\"/announce/announcement\">고객센터</a>\r\n");
      out.write("\t\t\t\t\t\t<ul class= \"submenu navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"/announce/announcement\" >공지사항</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a class=\"nav-link\" href=\"/board/write\" >문의사항</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" id=\"menubutton\">\r\n");
      out.write("\t      \t\t\t<span></span>\r\n");
      out.write("     \t\t\t\t<span></span>\r\n");
      out.write("     \t\t\t\t<span></span>\r\n");
      out.write("    \t\t\t</button>\r\n");
      out.write("\t    \t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Main -->\r\n");
      out.write("\t\t<div class=\"container\" id=goodsmain>\r\n");
      out.write("\t\t\t<!-- sidebar -->\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- sidenav -->\r\n");
      out.write("\t<nav id=\"sidebar\">\r\n");
      out.write("\t\t<button class = \"close_button\" type=\"button\">\r\n");
      out.write("\t\t\t<img src=\"/resources/img/index/close.png\" alt=\"\" class = close_img >\r\n");
      out.write("\t\t</button>\r\n");
      out.write("   \t\t\t<ul class=\"sidebar-nav\">\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a  href=\"/sub/company\" class=\"sidebar_m sidebar_link\"  >회사소개</a>\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a  href=\"/sub/company\" class=\"sidebar_s sidebar_link\"  >인사말</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a  href=\"/sub/history\" class=\"sidebar_s sidebar_link\"  >연혁</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a  href=\"/sub/location\" class=\"sidebar_s sidebar_link\"  >찾아오시는 길</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li >\r\n");
      out.write("\t\t\t\t<a  href=\"/sub/business\" class=\"sidebar_m sidebar_link\"  >사업소개</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li >\r\n");
      out.write("\t\t\t\t<a  href=\"/sub/goods\" class=\"sidebar_m sidebar_link\">제품소개</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t<li>\r\n");
      out.write("\t\t\t\t<a  href=\"/announce/announcement\" class=\"sidebar_m sidebar_link\">고객센터</a>\r\n");
      out.write("\t\t\t\t<ul >\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a  href=\"/announce/announcement\" class=\"sidebar_s sidebar_link\">공지사항</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"/board/write\" class=\"sidebar_s sidebar_link\">문의사항</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</nav>");
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"goods_top\">\r\n");
      out.write("\t\t\t\t<div class=\"goods_intro\">\r\n");
      out.write("\t\t\t\t\t<span><strong>제품소개</strong></span>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"goods_bottom text-center\">\r\n");
      out.write("\t\t\t\t<table class=\"goods_menu\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title1\">상품</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title1\">이름</td>\r\n");
      out.write("\t\t\t\t\t\t<td>간략설명</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<table class=\"goods_table\">\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title2\"><img src=\"/resources/img/goods/goods1.png\" class=goods_img alt=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title2\"><p>전자 미스트</p></td>\r\n");
      out.write("\t\t\t\t\t\t<td><p>내장 배터리를 이용하여 반 영구적 사용이 가능한 미스트</p></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title2\"><img src=\"/resources/img/goods/goods2.png\" class=goods_img alt=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title2\"><p>피트러스 PLUS</p></td>\r\n");
      out.write("\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t<p>시간과 장소에 구애 받지 않고 사용자의 신체 구성 측정 및 분석 가능</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>일관된 측정을 통해 신체 각 구성 요소에 대한 그래프 제공</p>\r\n");
      out.write("\t\t\t\t\t\t\t<p>측정결과 기반의 데이터를 통해 사용자의 맞춤 관리 가능</p>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title2\"><img src=\"/resources/img/goods/goods3.png\" class=goods_img alt=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title2\"><p>버스 광고 장치(CMS)</p></td>\r\n");
      out.write("\t\t\t\t\t\t<td><p>정류장의 와이파이를 통해 광고 데이터를 받아</p> <p>버스 내 장치를 통해 광고 하는 시스템</p></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title2\"><img src=\"/resources/img/goods/goods4.png\" class=goods_img alt=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title2\"><p>LED 디스플레이</p> <p>투명 패널</p></td>\r\n");
      out.write("\t\t\t\t\t\t<td><p>투명하고 유연한 대형 LED 패널</p></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title2\"><img src=\"/resources/img/goods/goods5.png\" class=goods_img alt=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title2\"><p>미세 먼지 측정기</p></td>\r\n");
      out.write("\t\t\t\t\t\t<td><p>센서를 통해 미세 먼지를 측정하는 기기</p></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title2\"><img src=\"/resources/img/goods/goods6.png\" class=goods_img alt=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title2\"><p>MR-450 선박 식별장치</p></td>\r\n");
      out.write("\t\t\t\t\t\t<td><p>GPS, VHF 정보를 이더넷으로 변환</p> <p>리눅스 탑재</p></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title2\"><img src=\"/resources/img/goods/goods7.png\" class=goods_img alt=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title2\"><p>썬바이저 타입 HUD</p></td>\r\n");
      out.write("\t\t\t\t\t\t<td><p>HUD를 썬바이저로 만들어 편리하게 사용자에게 정보를 제공 하는 기기</p> <p>리눅스 탑재</p></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title2\"><img src=\"/resources/img/goods/goods8.png\" class=goods_img alt=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title2\"><p>영상처리 보드</p></td>\r\n");
      out.write("\t\t\t\t\t\t<td><p>영상 신호를 받아 처리하는 DSP 보드</p></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title2\"><img src=\"/resources/img/goods/goods9.png\" class=goods_img alt=\"\"></td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"goods_title2\"><p>사출품 불량 검사 알고리즘</p></td>\r\n");
      out.write("\t\t\t\t\t\t<td><p>제품의 불량을 검사하는 알고리즘 보드</p></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!-- Footer -->\t\r\n");
      out.write("\t    <footer class=\"footer\" id=\"footer\">\r\n");
      out.write("\t\t    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<div class=\"address\">\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<p class=\" txtBase\">\r\n");
      out.write("\t\t\t\t\t대표자(성명) : 김병용&nbsp;&nbsp;사업자 등록번호 : 375-85-00293, 314-86-5779<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t포항 \t본사 \t주소 : (37748) 경북 포항시 북구 중흥로 265 (죽도동) 성원메디컬 108호<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t대전 연구소 주소 : (34027) 대전광역시 유성구 테크노9로 35 (탑립동) 지능로봇산업화센터 401호 <br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\t전화 : 070-4265-3411&nbsp;&nbsp;팩스 : 070-4015-0616&nbsp;&nbsp;\r\n");
      out.write("\t\t\t\t\t<a href=\"../board/write\"><img class=mail src=\"/resources/img/index/mail.png\" alt=\"\"></a>\r\n");
      out.write("\t\t\t\t</p> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\t</footer>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<script src=\"/resources/jquery/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"/resources/jquery/jstyle.js\"></script>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/sub/goods.jsp(11,14) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/css/style.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
